### ISSUE TITLE
可能的内存泄露问题

### ISSUE THREAD

**Issue by p3p3pp3** [lz1998/ssr-echarts#2]
首先感谢您分享这个项目，使用非常方便。
在测试中发现，随着生成图标数量的增加，内存占用也几乎是线性的不断递增。
以您demo中的示例请求为例：

![image](https://user-images.githubusercontent.com/3984167/141234571-a69dd9f2-8312-46d5-987c-6019eb0b85bf.png)

每次请求大概都会增加2-3MB的内存使用。

这是我按F5刷新一段时间后的内存占用情况：

![屏幕截图 2021-11-11 115515](https://user-images.githubusercontent.com/3984167/141234744-50dc9bc8-c172-4df6-9605-26d74cb1e184.png)

**Comment by lz1998** [comment]
> 首先感谢您分享这个项目，使用非常方便。 在测试中发现，随着生成图标数量的增加，内存占用也几乎是线性的不断递增。 以您demo中的示例请求为例：
> 
> ![image](https://user-images.githubusercontent.com/3984167/141234571-a69dd9f2-8312-46d5-987c-6019eb0b85bf.png)
> 
> 每次请求大概都会增加2-3MB的内存使用。
> 
> 这是我按F5刷新一段时间后的内存占用情况：
> 
> ![屏幕截图 2021-11-11 115515](https://user-images.githubusercontent.com/3984167/141234744-50dc9bc8-c172-4df6-9605-26d74cb1e184.png)

fix了，可以拉一下最新的image

**Comment by p3p3pp3** [comment]
感谢您的修订！测试没问题！

**Comment by p3p3pp3** [comment]
![image](https://user-images.githubusercontent.com/3984167/141245684-837012fc-7575-45f4-bab8-fe1d1ba12d02.png)

您好，刚发现有新的问题产生，之前绘制的图叠加起来了。

**Comment by p3p3pp3** [comment]
#3 我提交了一个PR，供参考。

**Comment by lz1998** [comment]
> #3 我提交了一个PR，供参考。

单实例复用canvas会比较好，已经修复了，你再拉一下镜像试试看

**Comment by p3p3pp3** [comment]
我对node不熟悉，但是单实例会不会在并发的时候出现错误，将不同的请求绘制在一个canvas上呢？

**Comment by lz1998** [comment]
> 我对node不熟悉，但是单实例会不会在并发的时候出现错误，将不同的请求绘制在一个canvas上呢？

JS是单线程的，不会出错

**Comment by p3p3pp3** [comment]
> > 我对node不熟悉，但是单实例会不会在并发的时候出现错误，将不同的请求绘制在一个canvas上呢？
> 
> JS是单线程的，不会出错

OK，了解了！
